name: ps11-docker-dev


volumes:
  db_data:

services:
  db:
    image: postgres:15
    container_name: ps11-db
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    image: redis:7.0.5-alpine
    container_name: ps11-redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379