networks:
  ps11-network:
    driver: bridge

volumes:
  db_data:
  media:

services:
  db:
    image: postgres:15
    container_name: ps11-db
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    networks:
      - ps11-network

  redis:
    image: redis:7.0.5-alpine
    container_name: ps11-redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    networks:
      - ps11-network

  backend:
    build: ./backend/
    container_name: ps11-backend
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/logs:/app/logs
      - media:/app/media
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - ps11-network
    restart: always
  
  frontend:
    build:
      context: ./frontend/
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_SMARTCAPTCHA_SITEKEY=${NEXT_PUBLIC_SMARTCAPTCHA_SITEKEY}
    container_name: ps11-frontend
    networks:
      - ps11-network
    restart: always

  nginx:
    build: ./nginx/
    container_name: ps11-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - media:/media
    env_file: .env
    depends_on:
      - backend
    networks:
      - ps11-network
    restart: always
